### ISSUE TITLE
Providing skip-path overrides bearer.yml values

### ISSUE THREAD

**Issue by mhp-borisbojic** [Bearer/curio-action#57]
When using skip-path within the Github Action workflow, it seems to overwrite all values of skip-path defined in the bearer.yml, e.g.:

```
      - name: Bearer scan
        uses: bearer/bearer-action@v2
        with:
          config-file: 'bearer.yml'
          skip-path: 'consent-management/*'
```

In the bearer.yml this additional paths are set (and then ignored):

```
  skip-path: [.nx/*, node_modules/*, lambda-proxy.ts, scripts/*]
```

Is this an expected behavoir?
